// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeCasino.Data.Data;

#nullable disable

namespace SafeCasino.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215201904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "player-user-id",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            Balance = 10000m,
                            ConcurrencyStamp = "becca7fb-7b4f-4ec9-a850-0ab622f8a026",
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@safecasino.be",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsVerified = true,
                            LastName = "Casino",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SAFECASINO.BE",
                            NormalizedUserName = "ADMIN@SAFECASINO.BE",
                            PasswordHash = "AQAAAAIAAYagAAAAEC3srrovx5XlEJ9D/cbAPfv29Q0RYPhhUYsQTlx0OOkhT4kTG1at1M1fyoat3ziHkA==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2025, 12, 15, 21, 19, 2, 549, DateTimeKind.Local).AddTicks(7316),
                            SecurityStamp = "75102ca7-17e1-441e-8906-9290aa208310",
                            TwoFactorEnabled = false,
                            UserName = "admin@safecasino.be"
                        },
                        new
                        {
                            Id = "player-user-id",
                            AccessFailedCount = 0,
                            Balance = 500m,
                            ConcurrencyStamp = "a2f40ad7-dfc2-460f-bc87-4345213f6002",
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "speler@safecasino.be",
                            EmailConfirmed = true,
                            FirstName = "Jan",
                            IsVerified = true,
                            LastName = "Janssens",
                            LockoutEnabled = false,
                            NormalizedEmail = "SPELER@SAFECASINO.BE",
                            NormalizedUserName = "SPELER@SAFECASINO.BE",
                            PasswordHash = "AQAAAAIAAYagAAAAEH3n73TlsYXPL7Aaq9oo39bhdqv8GYfjoA3Ir+qUbMb2OLBszSNj7cLo7nBZRZB7+Q==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2025, 12, 15, 21, 19, 2, 705, DateTimeKind.Local).AddTicks(8195),
                            SecurityStamp = "0c19511e-55ad-4431-adc9-52c1d97a3a3c",
                            TwoFactorEnabled = false,
                            UserName = "speler@safecasino.be"
                        });
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.CasinoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPopular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MaximumBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<decimal>("RtpPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsNew");

                    b.HasIndex("IsPopular");

                    b.HasIndex("Name");

                    b.HasIndex("ProviderId");

                    b.ToTable("CasinoGames", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 6, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(4635),
                            Description = "Traditionele blackjack met standaard regels en uitbetalingen",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 1000m,
                            MinimumBet = 1m,
                            Name = "Classic Blackjack",
                            PlayCount = 15420,
                            ProviderId = 1,
                            RtpPercentage = 99.41m,
                            ThumbnailUrl = "/images/games/classic-blackjack.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 4, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(6061),
                            Description = "Europese variant met hole card regel",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 2000m,
                            MinimumBet = 5m,
                            Name = "European Blackjack",
                            PlayCount = 12350,
                            ProviderId = 2,
                            RtpPercentage = 99.60m,
                            ThumbnailUrl = "/images/games/european-blackjack.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 2, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(6083),
                            Description = "Amerikaanse blackjack variant met late surrender optie",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 1500m,
                            MinimumBet = 2m,
                            Name = "Atlantic City Blackjack",
                            PlayCount = 8920,
                            ProviderId = 3,
                            RtpPercentage = 99.65m,
                            ThumbnailUrl = "/images/games/atlantic-blackjack.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 30, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(6093),
                            Description = "Blackjack met extra side bet op pairs",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = false,
                            MaximumBet = 500m,
                            MinimumBet = 1m,
                            Name = "Perfect Pairs Blackjack",
                            PlayCount = 3450,
                            ProviderId = 4,
                            RtpPercentage = 98.87m,
                            ThumbnailUrl = "/images/games/perfect-pairs-blackjack.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 8, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(6150),
                            Description = "Beide dealer kaarten zijn zichtbaar",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 1000m,
                            MinimumBet = 5m,
                            Name = "Double Exposure Blackjack",
                            PlayCount = 5670,
                            ProviderId = 5,
                            RtpPercentage = 99.33m,
                            ThumbnailUrl = "/images/games/double-exposure-blackjack.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 12, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7561),
                            Description = "Exclusieve live blackjack tafel met professionele dealers",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 10000m,
                            MinimumBet = 50m,
                            Name = "Live Blackjack VIP",
                            PlayCount = 23450,
                            ProviderId = 2,
                            RtpPercentage = 99.28m,
                            ThumbnailUrl = "/images/games/live-blackjack-vip.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 9, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7577),
                            Description = "Authentieke roulette ervaring met live dealer",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 5000m,
                            MinimumBet = 1m,
                            Name = "Live Roulette",
                            PlayCount = 34560,
                            ProviderId = 2,
                            RtpPercentage = 97.30m,
                            ThumbnailUrl = "/images/games/live-roulette.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 3, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7658),
                            Description = "Klassiek baccarat spel met live dealers",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 15000m,
                            MinimumBet = 10m,
                            Name = "Live Baccarat",
                            PlayCount = 19870,
                            ProviderId = 2,
                            RtpPercentage = 98.94m,
                            ThumbnailUrl = "/images/games/live-baccarat.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7670),
                            Description = "Poker variant tegen de dealer in live setting",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = false,
                            MaximumBet = 3000m,
                            MinimumBet = 5m,
                            Name = "Live Casino Hold'em",
                            PlayCount = 4560,
                            ProviderId = 2,
                            RtpPercentage = 97.84m,
                            ThumbnailUrl = "/images/games/live-casino-holdem.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 5, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7690),
                            Description = "Money wheel spel met live presentator",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 2000m,
                            MinimumBet = 0.10m,
                            Name = "Live Dream Catcher",
                            PlayCount = 28930,
                            ProviderId = 2,
                            RtpPercentage = 95.80m,
                            ThumbnailUrl = "/images/games/live-dream-catcher.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 6, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7719),
                            Description = "Klassieke Europese roulette met single zero",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 1000m,
                            MinimumBet = 0.10m,
                            Name = "European Roulette",
                            PlayCount = 45620,
                            ProviderId = 1,
                            RtpPercentage = 97.30m,
                            ThumbnailUrl = "/images/games/european-roulette.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 10, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7753),
                            Description = "Franse variant met La Partage regel",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 2000m,
                            MinimumBet = 1m,
                            Name = "French Roulette",
                            PlayCount = 32450,
                            ProviderId = 1,
                            RtpPercentage = 98.65m,
                            ThumbnailUrl = "/images/games/french-roulette.jpg"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 4, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7765),
                            Description = "Amerikaanse variant met double zero",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 1500m,
                            MinimumBet = 0.50m,
                            Name = "American Roulette",
                            PlayCount = 18760,
                            ProviderId = 3,
                            RtpPercentage = 94.74m,
                            ThumbnailUrl = "/images/games/american-roulette.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 10, 31, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7788),
                            Description = "Snellere roulette variant met kortere rondes",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = true,
                            MaximumBet = 500m,
                            MinimumBet = 0.20m,
                            Name = "Speed Roulette",
                            PlayCount = 12340,
                            ProviderId = 4,
                            RtpPercentage = 97.30m,
                            ThumbnailUrl = "/images/games/speed-roulette.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 7, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7865),
                            Description = "Speel op meerdere wielen tegelijk",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 100m,
                            MinimumBet = 0.10m,
                            Name = "Multi-Wheel Roulette",
                            PlayCount = 8920,
                            ProviderId = 5,
                            RtpPercentage = 97.30m,
                            ThumbnailUrl = "/images/games/multi-wheel-roulette.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 12, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7883),
                            Description = "Meest populaire poker variant wereldwijd",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 5000m,
                            MinimumBet = 1m,
                            Name = "Texas Hold'em Poker",
                            PlayCount = 56780,
                            ProviderId = 1,
                            RtpPercentage = 98.00m,
                            ThumbnailUrl = "/images/games/texas-holdem.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 8, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7894),
                            Description = "Tropische poker variant met progressieve jackpot",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 2000m,
                            MinimumBet = 2m,
                            Name = "Caribbean Stud Poker",
                            PlayCount = 14560,
                            ProviderId = 3,
                            RtpPercentage = 97.48m,
                            ThumbnailUrl = "/images/games/caribbean-stud.jpg"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7904),
                            Description = "Snelle poker variant met drie kaarten",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 1000m,
                            MinimumBet = 1m,
                            Name = "Three Card Poker",
                            PlayCount = 23450,
                            ProviderId = 4,
                            RtpPercentage = 96.63m,
                            ThumbnailUrl = "/images/games/three-card-poker.jpg"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 25, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7933),
                            Description = "Chinese poker variant met twee handen",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = false,
                            MaximumBet = 3000m,
                            MinimumBet = 5m,
                            Name = "Pai Gow Poker",
                            PlayCount = 3890,
                            ProviderId = 5,
                            RtpPercentage = 97.27m,
                            ThumbnailUrl = "/images/games/pai-gow-poker.jpg"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 2, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7945),
                            Description = "Klassieke video poker met standaard uitbetalingstabel",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 100m,
                            MinimumBet = 0.25m,
                            Name = "Video Poker Jacks or Better",
                            PlayCount = 34670,
                            ProviderId = 1,
                            RtpPercentage = 99.54m,
                            ThumbnailUrl = "/images/games/video-poker-jacks.jpg"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 12, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7978),
                            Description = "Iconische slot met expanding wilds en re-spins",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 100m,
                            MinimumBet = 0.10m,
                            Name = "Starburst",
                            PlayCount = 123450,
                            ProviderId = 1,
                            RtpPercentage = 96.09m,
                            ThumbnailUrl = "/images/games/starburst.jpg"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 8, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(7989),
                            Description = "Egyptische avonturen met expanding symbols",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 100m,
                            MinimumBet = 0.01m,
                            Name = "Book of Dead",
                            PlayCount = 98760,
                            ProviderId = 4,
                            RtpPercentage = 96.21m,
                            ThumbnailUrl = "/images/games/book-of-dead.jpg"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 12, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(8000),
                            Description = "Progressieve jackpot slot met safari thema",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 6.25m,
                            MinimumBet = 0.25m,
                            Name = "Mega Moolah",
                            PlayCount = 145670,
                            ProviderId = 3,
                            RtpPercentage = 88.12m,
                            ThumbnailUrl = "/images/games/mega-moolah.jpg"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 8, 15, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(8010),
                            Description = "Avonturenslot met avalanche feature",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 50m,
                            MinimumBet = 0.20m,
                            Name = "Gonzo's Quest",
                            PlayCount = 87650,
                            ProviderId = 1,
                            RtpPercentage = 95.97m,
                            ThumbnailUrl = "/images/games/gonzos-quest.jpg"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 10, 16, 21, 19, 2, 842, DateTimeKind.Local).AddTicks(8021),
                            Description = "Kleurrijke fruitmachine met tumble feature",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = true,
                            MaximumBet = 100m,
                            MinimumBet = 0.20m,
                            Name = "Sweet Bonanza",
                            PlayCount = 45890,
                            ProviderId = 5,
                            RtpPercentage = 96.51m,
                            ThumbnailUrl = "/images/games/sweet-bonanza.jpg"
                        });
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Klassieke kaartspellen waarbij je probeert zo dicht mogelijk bij 21 te komen",
                            DisplayOrder = 1,
                            IconUrl = "/images/categories/blackjack.svg",
                            IsActive = true,
                            Name = "Blackjack"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Speel live met echte dealers via videoverbinding",
                            DisplayOrder = 2,
                            IconUrl = "/images/categories/live-casino.svg",
                            IsActive = true,
                            Name = "Live Casino"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Draai aan het rad en voorspel waar de bal zal landen",
                            DisplayOrder = 3,
                            IconUrl = "/images/categories/roulette.svg",
                            IsActive = true,
                            Name = "Roulette"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test je pokerskills tegen andere spelers",
                            DisplayOrder = 4,
                            IconUrl = "/images/categories/poker.svg",
                            IsActive = true,
                            Name = "Poker"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Gokkasten met verschillende thema's en jackpots",
                            DisplayOrder = 5,
                            IconUrl = "/images/categories/slots.svg",
                            IsActive = true,
                            Name = "Slots"
                        });
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.GameProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameProviders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Toonaangevende provider van premium gaming oplossingen",
                            IsActive = true,
                            LogoUrl = "/images/providers/netent.png",
                            Name = "NetEnt",
                            WebsiteUrl = "https://www.netent.com"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Specialist in live casino games",
                            IsActive = true,
                            LogoUrl = "/images/providers/evolution.png",
                            Name = "Evolution Gaming",
                            WebsiteUrl = "https://www.evolution.com"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Een van de oudste en meest gerespecteerde game developers",
                            IsActive = true,
                            LogoUrl = "/images/providers/microgaming.png",
                            Name = "Microgaming",
                            WebsiteUrl = "https://www.microgaming.co.uk"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Innovatieve mobile-first game developer",
                            IsActive = true,
                            LogoUrl = "/images/providers/playngo.png",
                            Name = "Play'n GO",
                            WebsiteUrl = "https://www.playngo.com"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Multi-product content provider voor de gaming industrie",
                            IsActive = true,
                            LogoUrl = "/images/providers/pragmatic.png",
                            Name = "Pragmatic Play",
                            WebsiteUrl = "https://www.pragmaticplay.com"
                        });
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("IsApproved");

                    b.HasIndex("Rating");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("SafeCasino.Data.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "0a7b9bcd-cbaf-425b-885b-37d6260903ed",
                            Description = "Administrator met volledige toegang tot het systeem",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "39d4059d-106b-407a-ac1b-374e90573c35",
                            Description = "Moderator met beperkte beheersrechten",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "b046d096-7561-4de4-9723-ab535c50b3c8",
                            Description = "Standaard speler rol",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeCasino.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.CasinoGame", b =>
                {
                    b.HasOne("SafeCasino.Data.Entities.GameCategory", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeCasino.Data.Entities.GameProvider", "Provider")
                        .WithMany("Games")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.Review", b =>
                {
                    b.HasOne("SafeCasino.Data.Entities.CasinoGame", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeCasino.Data.Entities.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.CasinoGame", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.GameCategory", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.GameProvider", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
