// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeCasino.Data.Data;

#nullable disable

namespace SafeCasino.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124155426_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "player-user-id",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.CasinoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPopular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MaximumBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RtpPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsNew");

                    b.HasIndex("IsPopular");

                    b.HasIndex("Name");

                    b.HasIndex("ProviderId");

                    b.ToTable("CasinoGames", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 7, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(3079),
                            Description = "Traditionele blackjack met standaard regels en uitbetalingen",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 1000m,
                            MinimumBet = 1m,
                            Name = "Classic Blackjack",
                            PlayCount = 15420,
                            ProviderId = 1,
                            RtpPercentage = 99.41m,
                            ThumbnailUrl = "/images/games/classic-blackjack.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 5, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(4714),
                            Description = "Europese variant met hole card regel",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 2000m,
                            MinimumBet = 5m,
                            Name = "European Blackjack",
                            PlayCount = 12350,
                            ProviderId = 2,
                            RtpPercentage = 99.60m,
                            ThumbnailUrl = "/images/games/european-blackjack.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 3, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(4737),
                            Description = "Amerikaanse blackjack variant met late surrender optie",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 1500m,
                            MinimumBet = 2m,
                            Name = "Atlantic City Blackjack",
                            PlayCount = 8920,
                            ProviderId = 3,
                            RtpPercentage = 99.65m,
                            ThumbnailUrl = "/images/games/atlantic-blackjack.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 1, 9, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(4746),
                            Description = "Blackjack met extra side bet op pairs",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = false,
                            MaximumBet = 500m,
                            MinimumBet = 1m,
                            Name = "Perfect Pairs Blackjack",
                            PlayCount = 3450,
                            ProviderId = 4,
                            RtpPercentage = 98.87m,
                            ThumbnailUrl = "/images/games/perfect-pairs-blackjack.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 9, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(4954),
                            Description = "Beide dealer kaarten zijn zichtbaar",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 1000m,
                            MinimumBet = 5m,
                            Name = "Double Exposure Blackjack",
                            PlayCount = 5670,
                            ProviderId = 5,
                            RtpPercentage = 99.33m,
                            ThumbnailUrl = "/images/games/double-exposure-blackjack.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 1, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6395),
                            Description = "Exclusieve live blackjack tafel met professionele dealers",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 10000m,
                            MinimumBet = 50m,
                            Name = "Live Blackjack VIP",
                            PlayCount = 23450,
                            ProviderId = 2,
                            RtpPercentage = 99.28m,
                            ThumbnailUrl = "/images/games/live-blackjack-vip.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 10, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6438),
                            Description = "Authentieke roulette ervaring met live dealer",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 5000m,
                            MinimumBet = 1m,
                            Name = "Live Roulette",
                            PlayCount = 34560,
                            ProviderId = 2,
                            RtpPercentage = 97.30m,
                            ThumbnailUrl = "/images/games/live-roulette.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6449),
                            Description = "Klassiek baccarat spel met live dealers",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 15000m,
                            MinimumBet = 10m,
                            Name = "Live Baccarat",
                            PlayCount = 19870,
                            ProviderId = 2,
                            RtpPercentage = 98.94m,
                            ThumbnailUrl = "/images/games/live-baccarat.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 25, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6459),
                            Description = "Poker variant tegen de dealer in live setting",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = false,
                            MaximumBet = 3000m,
                            MinimumBet = 5m,
                            Name = "Live Casino Hold'em",
                            PlayCount = 4560,
                            ProviderId = 2,
                            RtpPercentage = 97.84m,
                            ThumbnailUrl = "/images/games/live-casino-holdem.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 6, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6469),
                            Description = "Money wheel spel met live presentator",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 2000m,
                            MinimumBet = 0.10m,
                            Name = "Live Dream Catcher",
                            PlayCount = 28930,
                            ProviderId = 2,
                            RtpPercentage = 95.80m,
                            ThumbnailUrl = "/images/games/live-dream-catcher.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6493),
                            Description = "Klassieke Europese roulette met single zero",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 1000m,
                            MinimumBet = 0.10m,
                            Name = "European Roulette",
                            PlayCount = 45620,
                            ProviderId = 1,
                            RtpPercentage = 97.30m,
                            ThumbnailUrl = "/images/games/european-roulette.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 11, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6505),
                            Description = "Franse variant met La Partage regel",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 2000m,
                            MinimumBet = 1m,
                            Name = "French Roulette",
                            PlayCount = 32450,
                            ProviderId = 1,
                            RtpPercentage = 98.65m,
                            ThumbnailUrl = "/images/games/french-roulette.jpg"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 5, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6515),
                            Description = "Amerikaanse variant met double zero",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 1500m,
                            MinimumBet = 0.50m,
                            Name = "American Roulette",
                            PlayCount = 18760,
                            ProviderId = 3,
                            RtpPercentage = 94.74m,
                            ThumbnailUrl = "/images/games/american-roulette.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 10, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6542),
                            Description = "Snellere roulette variant met kortere rondes",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = true,
                            MaximumBet = 500m,
                            MinimumBet = 0.20m,
                            Name = "Speed Roulette",
                            PlayCount = 12340,
                            ProviderId = 4,
                            RtpPercentage = 97.30m,
                            ThumbnailUrl = "/images/games/speed-roulette.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 8, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6603),
                            Description = "Speel op meerdere wielen tegelijk",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 100m,
                            MinimumBet = 0.10m,
                            Name = "Multi-Wheel Roulette",
                            PlayCount = 8920,
                            ProviderId = 5,
                            RtpPercentage = 97.30m,
                            ThumbnailUrl = "/images/games/multi-wheel-roulette.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 1, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6617),
                            Description = "Meest populaire poker variant wereldwijd",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 5000m,
                            MinimumBet = 1m,
                            Name = "Texas Hold'em Poker",
                            PlayCount = 56780,
                            ProviderId = 1,
                            RtpPercentage = 98.00m,
                            ThumbnailUrl = "/images/games/texas-holdem.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 9, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6627),
                            Description = "Tropische poker variant met progressieve jackpot",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = false,
                            MaximumBet = 2000m,
                            MinimumBet = 2m,
                            Name = "Caribbean Stud Poker",
                            PlayCount = 14560,
                            ProviderId = 3,
                            RtpPercentage = 97.48m,
                            ThumbnailUrl = "/images/games/caribbean-stud.jpg"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 2, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6636),
                            Description = "Snelle poker variant met drie kaarten",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 1000m,
                            MinimumBet = 1m,
                            Name = "Three Card Poker",
                            PlayCount = 23450,
                            ProviderId = 4,
                            RtpPercentage = 96.63m,
                            ThumbnailUrl = "/images/games/three-card-poker.jpg"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 1, 4, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6646),
                            Description = "Chinese poker variant met twee handen",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = false,
                            MaximumBet = 3000m,
                            MinimumBet = 5m,
                            Name = "Pai Gow Poker",
                            PlayCount = 3890,
                            ProviderId = 5,
                            RtpPercentage = 97.27m,
                            ThumbnailUrl = "/images/games/pai-gow-poker.jpg"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 3, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6656),
                            Description = "Klassieke video poker met standaard uitbetalingstabel",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 100m,
                            MinimumBet = 0.25m,
                            Name = "Video Poker Jacks or Better",
                            PlayCount = 34670,
                            ProviderId = 1,
                            RtpPercentage = 99.54m,
                            ThumbnailUrl = "/images/games/video-poker-jacks.jpg"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 1, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6667),
                            Description = "Iconische slot met expanding wilds en re-spins",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 100m,
                            MinimumBet = 0.10m,
                            Name = "Starburst",
                            PlayCount = 123450,
                            ProviderId = 1,
                            RtpPercentage = 96.09m,
                            ThumbnailUrl = "/images/games/starburst.jpg"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 9, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6677),
                            Description = "Egyptische avonturen met expanding symbols",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 100m,
                            MinimumBet = 0.01m,
                            Name = "Book of Dead",
                            PlayCount = 98760,
                            ProviderId = 4,
                            RtpPercentage = 96.21m,
                            ThumbnailUrl = "/images/games/book-of-dead.jpg"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 1, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6687),
                            Description = "Progressieve jackpot slot met safari thema",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 6.25m,
                            MinimumBet = 0.25m,
                            Name = "Mega Moolah",
                            PlayCount = 145670,
                            ProviderId = 3,
                            RtpPercentage = 88.12m,
                            ThumbnailUrl = "/images/games/mega-moolah.jpg"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 9, 24, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6696),
                            Description = "Avonturenslot met avalanche feature",
                            IsAvailable = true,
                            IsNew = false,
                            IsPopular = true,
                            MaximumBet = 50m,
                            MinimumBet = 0.20m,
                            Name = "Gonzo's Quest",
                            PlayCount = 87650,
                            ProviderId = 1,
                            RtpPercentage = 95.97m,
                            ThumbnailUrl = "/images/games/gonzos-quest.jpg"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 11, 25, 16, 54, 24, 902, DateTimeKind.Local).AddTicks(6706),
                            Description = "Kleurrijke fruitmachine met tumble feature",
                            IsAvailable = true,
                            IsNew = true,
                            IsPopular = true,
                            MaximumBet = 100m,
                            MinimumBet = 0.20m,
                            Name = "Sweet Bonanza",
                            PlayCount = 45890,
                            ProviderId = 5,
                            RtpPercentage = 96.51m,
                            ThumbnailUrl = "/images/games/sweet-bonanza.jpg"
                        });
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 896, DateTimeKind.Utc).AddTicks(6257),
                            Description = "Klassieke kaartspellen waarbij je probeert zo dicht mogelijk bij 21 te komen",
                            DisplayOrder = 1,
                            IconUrl = "/images/categories/blackjack.svg",
                            IsActive = true,
                            Name = "Blackjack"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 896, DateTimeKind.Utc).AddTicks(8957),
                            Description = "Speel live met echte dealers via videoverbinding",
                            DisplayOrder = 2,
                            IconUrl = "/images/categories/live-casino.svg",
                            IsActive = true,
                            Name = "Live Casino"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 896, DateTimeKind.Utc).AddTicks(8964),
                            Description = "Draai aan het rad en voorspel waar de bal zal landen",
                            DisplayOrder = 3,
                            IconUrl = "/images/categories/roulette.svg",
                            IsActive = true,
                            Name = "Roulette"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 896, DateTimeKind.Utc).AddTicks(8967),
                            Description = "Test je pokerskills tegen andere spelers",
                            DisplayOrder = 4,
                            IconUrl = "/images/categories/poker.svg",
                            IsActive = true,
                            Name = "Poker"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 896, DateTimeKind.Utc).AddTicks(8970),
                            Description = "Gokkasten met verschillende thema's en jackpots",
                            DisplayOrder = 5,
                            IconUrl = "/images/categories/slots.svg",
                            IsActive = true,
                            Name = "Slots"
                        });
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("IsApproved");

                    b.HasIndex("Rating");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);

                    b.HasDiscriminator().HasValue("Review");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SafeCasino.Data.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "5be9da2e-46e6-4217-a3f2-ff9d9f3cf495",
                            CreatedAt = new DateTime(2026, 1, 24, 15, 54, 24, 588, DateTimeKind.Utc).AddTicks(8915),
                            Description = "Administrator met volledige toegang tot het systeem",
                            IsActive = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "8c22d1db-ca4f-4c2c-a3e0-befa54d9b213",
                            CreatedAt = new DateTime(2026, 1, 24, 15, 54, 24, 592, DateTimeKind.Utc).AddTicks(3370),
                            Description = "Moderator met beperkte beheersrechten",
                            IsActive = true,
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "8710693b-56ce-4739-a3bf-dfcd9419a788",
                            CreatedAt = new DateTime(2026, 1, 24, 15, 54, 24, 592, DateTimeKind.Utc).AddTicks(3477),
                            Description = "Standaard speler rol",
                            IsActive = true,
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        });
                });

            modelBuilder.Entity("SafeCasino.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            Balance = 10000m,
                            ConcurrencyStamp = "415515f2-405d-4105-81ca-b06fb8271852",
                            CreatedAt = new DateTime(2026, 1, 24, 15, 54, 24, 606, DateTimeKind.Utc).AddTicks(4004),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@safecasino.be",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Casino",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SAFECASINO.BE",
                            NormalizedUserName = "ADMIN@SAFECASINO.BE",
                            PasswordHash = "AQAAAAIAAYagAAAAEINpNHbzDQV9dUF/G4npb5A1P2xkYU9XP9lNz5YE3uEibW0dex99tvBETlIblumL3Q==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2026, 1, 24, 16, 54, 24, 607, DateTimeKind.Local).AddTicks(4777),
                            SecurityStamp = "63bee12b-9491-49e2-8913-ec5393fdf1ee",
                            TwoFactorEnabled = false,
                            UserName = "admin@safecasino.be"
                        },
                        new
                        {
                            Id = "player-user-id",
                            AccessFailedCount = 0,
                            Balance = 500m,
                            ConcurrencyStamp = "df1b9d1d-08f9-4812-89a3-df199182e901",
                            CreatedAt = new DateTime(2026, 1, 24, 15, 54, 24, 761, DateTimeKind.Utc).AddTicks(6607),
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "speler@safecasino.be",
                            EmailConfirmed = true,
                            FirstName = "Jan",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Janssens",
                            LockoutEnabled = false,
                            NormalizedEmail = "SPELER@SAFECASINO.BE",
                            NormalizedUserName = "SPELER@SAFECASINO.BE",
                            PasswordHash = "AQAAAAIAAYagAAAAEGCRyrkU2aTeVyCrK6tMLa6pY2edS6mdZy4CdYgPxqeuNjLTTgUpEn8++k5Nac9jEQ==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2026, 1, 24, 16, 54, 24, 761, DateTimeKind.Local).AddTicks(6783),
                            SecurityStamp = "fad41ca4-dd61-4ae9-b2b1-94fde55ac500",
                            TwoFactorEnabled = false,
                            UserName = "speler@safecasino.be"
                        });
                });

            modelBuilder.Entity("SafeCasino.Data.Identity.GameProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameProviders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 897, DateTimeKind.Utc).AddTicks(4664),
                            Description = "Toonaangevende provider van premium gaming oplossingen",
                            IsActive = true,
                            LogoUrl = "/images/providers/netent.png",
                            Name = "NetEnt",
                            WebsiteUrl = "https://www.netent.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 897, DateTimeKind.Utc).AddTicks(6589),
                            Description = "Specialist in live casino games",
                            IsActive = true,
                            LogoUrl = "/images/providers/evolution.png",
                            Name = "Evolution Gaming",
                            WebsiteUrl = "https://www.evolution.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 897, DateTimeKind.Utc).AddTicks(6595),
                            Description = "Een van de oudste en meest gerespecteerde game developers",
                            IsActive = true,
                            LogoUrl = "/images/providers/microgaming.png",
                            Name = "Microgaming",
                            WebsiteUrl = "https://www.microgaming.co.uk"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 897, DateTimeKind.Utc).AddTicks(6598),
                            Description = "Innovatieve mobile-first game developer",
                            IsActive = true,
                            LogoUrl = "/images/providers/playngo.png",
                            Name = "Play'n GO",
                            WebsiteUrl = "https://www.playngo.com"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 24, 15, 54, 24, 897, DateTimeKind.Utc).AddTicks(6601),
                            Description = "Multi-product content provider voor de gaming industrie",
                            IsActive = true,
                            LogoUrl = "/images/providers/pragmatic.png",
                            Name = "Pragmatic Play",
                            WebsiteUrl = "https://www.pragmaticplay.com"
                        });
                });

            modelBuilder.Entity("UserFavoriteGames", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavoriteGames");
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.GameReview", b =>
                {
                    b.HasBaseType("SafeCasino.Data.Entities.Review");

                    b.ToTable("Reviews", (string)null);

                    b.HasDiscriminator().HasValue("GameReview");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeCasino.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SafeCasino.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.CasinoGame", b =>
                {
                    b.HasOne("SafeCasino.Data.Entities.GameCategory", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeCasino.Data.Identity.GameProvider", "Provider")
                        .WithMany("Games")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.Review", b =>
                {
                    b.HasOne("SafeCasino.Data.Entities.CasinoGame", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeCasino.Data.Identity.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserFavoriteGames", b =>
                {
                    b.HasOne("SafeCasino.Data.Entities.CasinoGame", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeCasino.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.CasinoGame", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SafeCasino.Data.Entities.GameCategory", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SafeCasino.Data.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SafeCasino.Data.Identity.GameProvider", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
