// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeCasino.Data;

#nullable disable

namespace SafeCasino.Migrations
{
    [DbContext(typeof(SafeCasinoDbContext))]
    [Migration("20251128063342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeCasino.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GameUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("HasJackpot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxBet")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinBet")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RTP")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2025, 10, 14, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9177),
                            Category = 0,
                            Description = "Speel Book of Ra en ervaar de spanning!",
                            GameUrl = "/play/2",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 500m,
                            MinBet = 0.10m,
                            Name = "Book of Ra",
                            Provider = "Pragmatic Play",
                            RTP = 94.563629193493924m,
                            ThumbnailUrl = "/images/games/slots/book-of-ra.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2025, 8, 25, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9210),
                            Category = 0,
                            Description = "Speel Starburst en ervaar de spanning!",
                            GameUrl = "/play/3",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 500m,
                            MinBet = 0.10m,
                            Name = "Starburst",
                            Provider = "Evolution",
                            RTP = 94.673736896679614m,
                            ThumbnailUrl = "/images/games/slots/starburst.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2025, 9, 26, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9324),
                            Category = 0,
                            Description = "Speel Gonzo's Quest en ervaar de spanning!",
                            GameUrl = "/play/4",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 0.10m,
                            Name = "Gonzo's Quest",
                            Provider = "Pragmatic Play",
                            RTP = 96.05169116614931m,
                            ThumbnailUrl = "/images/games/slots/gonzos-quest.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AddedDate = new DateTime(2025, 8, 27, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9344),
                            Category = 0,
                            Description = "Speel Mega Moolah en ervaar de spanning!",
                            GameUrl = "/play/5",
                            HasJackpot = false,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 0.10m,
                            Name = "Mega Moolah",
                            Provider = "Pragmatic Play",
                            RTP = 94.938353833248072m,
                            ThumbnailUrl = "/images/games/slots/mega-moolah.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AddedDate = new DateTime(2025, 7, 12, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9361),
                            Category = 0,
                            Description = "Speel Dead or Alive en ervaar de spanning!",
                            GameUrl = "/play/6",
                            HasJackpot = false,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 0.10m,
                            Name = "Dead or Alive",
                            Provider = "Evolution",
                            RTP = 95.28093274928673m,
                            ThumbnailUrl = "/images/games/slots/dead-or-alive.jpg"
                        },
                        new
                        {
                            Id = 6,
                            AddedDate = new DateTime(2025, 11, 16, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9389),
                            Category = 1,
                            Description = "Speel European Roulette en ervaar de spanning!",
                            GameUrl = "/play/7",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "European Roulette",
                            Provider = "Microgaming",
                            RTP = 96.06980439930679m,
                            ThumbnailUrl = "/images/games/roulette/european-roulette.jpg"
                        },
                        new
                        {
                            Id = 7,
                            AddedDate = new DateTime(2025, 7, 6, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9408),
                            Category = 1,
                            Description = "Speel American Roulette en ervaar de spanning!",
                            GameUrl = "/play/8",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "American Roulette",
                            Provider = "Pragmatic Play",
                            RTP = 96.30878741587921m,
                            ThumbnailUrl = "/images/games/roulette/american-roulette.jpg"
                        },
                        new
                        {
                            Id = 8,
                            AddedDate = new DateTime(2025, 3, 16, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9425),
                            Category = 1,
                            Description = "Speel French Roulette en ervaar de spanning!",
                            GameUrl = "/play/9",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "French Roulette",
                            Provider = "NetEnt",
                            RTP = 94.360450441185595m,
                            ThumbnailUrl = "/images/games/roulette/french-roulette.jpg"
                        },
                        new
                        {
                            Id = 9,
                            AddedDate = new DateTime(2025, 11, 12, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9448),
                            Category = 1,
                            Description = "Speel Lightning Roulette en ervaar de spanning!",
                            GameUrl = "/play/10",
                            HasJackpot = false,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "Lightning Roulette",
                            Provider = "Pragmatic Play",
                            RTP = 96.15988232854748m,
                            ThumbnailUrl = "/images/games/roulette/lightning-roulette.jpg"
                        },
                        new
                        {
                            Id = 10,
                            AddedDate = new DateTime(2025, 1, 2, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9468),
                            Category = 1,
                            Description = "Speel Immersive Roulette en ervaar de spanning!",
                            GameUrl = "/play/11",
                            HasJackpot = false,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "Immersive Roulette",
                            Provider = "Pragmatic Play",
                            RTP = 94.591045065126868m,
                            ThumbnailUrl = "/images/games/roulette/immersive-roulette.jpg"
                        },
                        new
                        {
                            Id = 11,
                            AddedDate = new DateTime(2025, 9, 21, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9489),
                            Category = 2,
                            Description = "Speel Classic Blackjack en ervaar de spanning!",
                            GameUrl = "/play/12",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "Classic Blackjack",
                            Provider = "Pragmatic Play",
                            RTP = 96.06565485618341m,
                            ThumbnailUrl = "/images/games/blackjack/classic-blackjack.jpg"
                        },
                        new
                        {
                            Id = 12,
                            AddedDate = new DateTime(2025, 4, 30, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9511),
                            Category = 2,
                            Description = "Speel Blackjack Pro en ervaar de spanning!",
                            GameUrl = "/play/13",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "Blackjack Pro",
                            Provider = "NetEnt",
                            RTP = 95.23279865143485m,
                            ThumbnailUrl = "/images/games/blackjack/blackjack-pro.jpg"
                        },
                        new
                        {
                            Id = 13,
                            AddedDate = new DateTime(2025, 5, 17, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9529),
                            Category = 2,
                            Description = "Speel Perfect Blackjack en ervaar de spanning!",
                            GameUrl = "/play/14",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "Perfect Blackjack",
                            Provider = "Pragmatic Play",
                            RTP = 94.0158194433971399m,
                            ThumbnailUrl = "/images/games/blackjack/perfect-blackjack.jpg"
                        },
                        new
                        {
                            Id = 14,
                            AddedDate = new DateTime(2025, 7, 11, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9547),
                            Category = 2,
                            Description = "Speel VIP Blackjack en ervaar de spanning!",
                            GameUrl = "/play/15",
                            HasJackpot = false,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "VIP Blackjack",
                            Provider = "Pragmatic Play",
                            RTP = 96.9934357083372m,
                            ThumbnailUrl = "/images/games/blackjack/vip-blackjack.jpg"
                        },
                        new
                        {
                            Id = 15,
                            AddedDate = new DateTime(2025, 11, 10, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9631),
                            Category = 2,
                            Description = "Speel Blackjack Switch en ervaar de spanning!",
                            GameUrl = "/play/16",
                            HasJackpot = false,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 500m,
                            MinBet = 1m,
                            Name = "Blackjack Switch",
                            Provider = "NetEnt",
                            RTP = 94.105358056773133m,
                            ThumbnailUrl = "/images/games/blackjack/blackjack-switch.jpg"
                        },
                        new
                        {
                            Id = 16,
                            AddedDate = new DateTime(2025, 10, 17, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9655),
                            Category = 3,
                            Description = "Speel Live Roulette en ervaar de spanning!",
                            GameUrl = "/play/17",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 1000m,
                            MinBet = 1m,
                            Name = "Live Roulette",
                            Provider = "Pragmatic Play",
                            RTP = 96.50582553749244m,
                            ThumbnailUrl = "/images/games/livecasino/live-roulette.jpg"
                        },
                        new
                        {
                            Id = 17,
                            AddedDate = new DateTime(2025, 8, 15, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9674),
                            Category = 3,
                            Description = "Speel Live Blackjack en ervaar de spanning!",
                            GameUrl = "/play/18",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 1000m,
                            MinBet = 1m,
                            Name = "Live Blackjack",
                            Provider = "Microgaming",
                            RTP = 97.08971329736044m,
                            ThumbnailUrl = "/images/games/livecasino/live-blackjack.jpg"
                        },
                        new
                        {
                            Id = 18,
                            AddedDate = new DateTime(2025, 11, 12, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9694),
                            Category = 3,
                            Description = "Speel Live Baccarat en ervaar de spanning!",
                            GameUrl = "/play/19",
                            HasJackpot = false,
                            IsNew = false,
                            IsPopular = false,
                            MaxBet = 1000m,
                            MinBet = 1m,
                            Name = "Live Baccarat",
                            Provider = "Evolution",
                            RTP = 94.574585939093766m,
                            ThumbnailUrl = "/images/games/livecasino/live-baccarat.jpg"
                        },
                        new
                        {
                            Id = 19,
                            AddedDate = new DateTime(2025, 11, 10, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9711),
                            Category = 3,
                            Description = "Speel Live Dream Catcher en ervaar de spanning!",
                            GameUrl = "/play/20",
                            HasJackpot = false,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 1000m,
                            MinBet = 1m,
                            Name = "Live Dream Catcher",
                            Provider = "Evolution",
                            RTP = 96.06365354268982m,
                            ThumbnailUrl = "/images/games/livecasino/live-dream-catcher.jpg"
                        },
                        new
                        {
                            Id = 20,
                            AddedDate = new DateTime(2025, 4, 13, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9728),
                            Category = 3,
                            Description = "Speel Live Monopoly en ervaar de spanning!",
                            GameUrl = "/play/21",
                            HasJackpot = false,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 1000m,
                            MinBet = 1m,
                            Name = "Live Monopoly",
                            Provider = "PlayTech",
                            RTP = 96.82632930522148m,
                            ThumbnailUrl = "/images/games/livecasino/live-monopoly.jpg"
                        },
                        new
                        {
                            Id = 21,
                            AddedDate = new DateTime(2025, 7, 18, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9749),
                            Category = 4,
                            Description = "Speel Mega Fortune en ervaar de spanning!",
                            GameUrl = "/play/22",
                            HasJackpot = true,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 200m,
                            MinBet = 0.20m,
                            Name = "Mega Fortune",
                            Provider = "Microgaming",
                            RTP = 94.0530150998630631m,
                            ThumbnailUrl = "/images/games/jackpot/mega-fortune.jpg"
                        },
                        new
                        {
                            Id = 22,
                            AddedDate = new DateTime(2025, 3, 11, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9768),
                            Category = 4,
                            Description = "Speel Hall of Gods en ervaar de spanning!",
                            GameUrl = "/play/23",
                            HasJackpot = true,
                            IsNew = false,
                            IsPopular = true,
                            MaxBet = 200m,
                            MinBet = 0.20m,
                            Name = "Hall of Gods",
                            Provider = "Microgaming",
                            RTP = 94.27464334306989m,
                            ThumbnailUrl = "/images/games/jackpot/hall-of-gods.jpg"
                        },
                        new
                        {
                            Id = 23,
                            AddedDate = new DateTime(2025, 11, 24, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9785),
                            Category = 4,
                            Description = "Speel Arabian Nights en ervaar de spanning!",
                            GameUrl = "/play/24",
                            HasJackpot = true,
                            IsNew = false,
                            IsPopular = false,
                            MaxBet = 200m,
                            MinBet = 0.20m,
                            Name = "Arabian Nights",
                            Provider = "NetEnt",
                            RTP = 95.85637431305664m,
                            ThumbnailUrl = "/images/games/jackpot/arabian-nights.jpg"
                        },
                        new
                        {
                            Id = 24,
                            AddedDate = new DateTime(2025, 5, 25, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9802),
                            Category = 4,
                            Description = "Speel Mega Moolah Isis en ervaar de spanning!",
                            GameUrl = "/play/25",
                            HasJackpot = true,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 200m,
                            MinBet = 0.20m,
                            Name = "Mega Moolah Isis",
                            Provider = "Pragmatic Play",
                            RTP = 95.75671793229725m,
                            ThumbnailUrl = "/images/games/jackpot/mega-moolah-isis.jpg"
                        },
                        new
                        {
                            Id = 25,
                            AddedDate = new DateTime(2025, 1, 30, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(9819),
                            Category = 4,
                            Description = "Speel Major Millions en ervaar de spanning!",
                            GameUrl = "/play/26",
                            HasJackpot = true,
                            IsNew = true,
                            IsPopular = false,
                            MaxBet = 200m,
                            MinBet = 0.20m,
                            Name = "Major Millions",
                            Provider = "PlayTech",
                            RTP = 94.0358116366135942m,
                            ThumbnailUrl = "/images/games/jackpot/major-millions.jpg"
                        });
                });

            modelBuilder.Entity("SafeCasino.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 28, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(8441),
                            PasswordHash = "User!321",
                            UserType = "User",
                            Username = "casinouser@ehb.be"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 28, 6, 33, 41, 358, DateTimeKind.Utc).AddTicks(8445),
                            PasswordHash = "Admin!321",
                            UserType = "Admin",
                            Username = "casinoadmin@ehb.be"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
