// Services/ILocalizationService.cs
namespace SafeCasino.Services
{
    public interface ILocalizationService
    {
        string GetString(string key, string language);
        Dictionary<string, string> GetAllStrings(string language);
    }
}

// Services/LocalizationService.cs
namespace SafeCasino.Services
{
    public class LocalizationService : ILocalizationService
    {
        private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            ["nl"] = new Dictionary<string, string>
            {
                // Common
                ["Home"] = "Home",
                ["Games"] = "Spellen",
                ["Login"] = "Inloggen",
                ["Register"] = "Registreren",
                ["AdminLogin"] = "Admin Inloggen",
                ["Username"] = "Gebruikersnaam",
                ["Password"] = "Wachtwoord",
                ["Email"] = "E-mail",
                ["RememberMe"] = "Onthoud mij",
                ["Error"] = "Fout",
                ["BackToHome"] = "Terug naar Home",
                ["WelcomeBack"] = "Welkom Terug",
                ["ForgotPassword"] = "Wachtwoord Vergeten",
                ["DontHaveAccount"] = "Heeft u nog geen account",
                ["OrLoginWith"] = "Of log in met",
                ["GetStarted"] = "Aan de slag",
                ["PlayNow"] = "Speel Nu",
                ["Roulette"] = "Roulette",
                ["Slots"] = "Slots",
                ["Blackjack"] = "Blackjack",
                ["Profile"] = "Profiel",
                ["Settings"] = "Instellingen",
                ["Logout"] = "Uitloggen",
                ["BackToGames"] = "Terug naar Spellen",
                ["GameDetails"] = "Speldetails",
                ["Popular"] = "Populair",
                ["New"] = "Nieuw",
                ["MinBet"] = "Min. Inzet",
                ["MaxBet"] = "Max. Inzet",
                ["Players"] = "Spelers",
                ["Rating"] = "Beoordeling",
                ["AddToFavorites"] = "Toevoegen aan Favorieten",
                ["LoginToPlay"] = "Log in om te Spelen",
                ["HowToPlay"] = "Hoe te Spelen",
                ["NoRulesAvailable"] = "Geen spelregels beschikbaar",
                ["SimilarGames"] = "Vergelijkbare Spellen",
                ["ComingSoon"] = "Binnenkort",
                ["EnterEmail"] = "Voer e-mail in",
                ["EnterPassword"] = "Voer wachtwoord in",
                ["WelcomeToSafeCasino"] = "Welkom bij SafeCasino",
                ["About"] = "Over",
                ["Privacy"] = "Privacy",
                ["Contact"] = "Contact",
                ["FAQ"] = "Veelgestelde Vragen",

                // Home Page
                ["HeroDescription"] = "Ervaar de spanning van topspellen in het veiligste online casino",
                ["WhyChooseUs"] = "Waarom voor ons kiezen?",
                ["SafeAndSecure"] = "Veilig en Beveiligd",
                ["SafeDescription"] = "SSL-versleuteling en beveiligde betalingen",
                ["FastPayouts"] = "Snelle Uitbetalingen",
                ["PayoutsDescription"] = "Ontvang uw winsten binnen 24 uur",
                ["Support247"] = "24/7 Ondersteuning",
                ["SupportDescription"] = "Altijd bereikbaar voor uw vragen",
                ["PopularGames"] = "Populaire Spellen",
                ["RouletteDescription"] = "Draai het wiel en win groot",
                ["SlotsDescription"] = "Honderden gokkasten met jackpots",
                ["BlackjackDescription"] = "Klassiek kaartspel met strategie",
                ["ActivePlayers"] = "Actieve Spelers",
                ["PaidOut"] = "Uitgekeerd",
                ["ReadyToStart"] = "Klaar om te beginnen?",
                ["CTADescription"] = "Word vandaag nog lid en ontvang uw welkomstbonus",
                ["JoinNow"] = "Meld je nu aan",
                ["FooterTagline"] = "Het meest vertrouwde online casino",
                ["QuickLinks"] = "Snelle Links",
                ["AllRightsReserved"] = "Alle rechten voorbehouden",

                // Games Page
                ["CasinoGames"] = "Casino Spellen",
                ["DiscoverGames"] = "Ontdek onze collectie van premium casinospellen",
                ["Search"] = "Zoeken",
                ["SearchGames"] = "Zoek spellen...",
                ["Categories"] = "Categorieën",
                ["AllCategories"] = "Alle Categorieën",
                ["Provider"] = "Aanbieder",
                ["AllProviders"] = "Alle Aanbieders",
                ["BetRange"] = "Inzetbereik",
                ["Min"] = "Min",
                ["Max"] = "Max",
                ["SpecialFeatures"] = "Speciale Functies",
                ["HasJackpot"] = "Heeft Jackpot",
                ["OnlyNew"] = "Alleen Nieuw",
                ["OnlyPopular"] = "Alleen Populair",
                ["SortBy"] = "Sorteer op",
                ["NameAZ"] = "Naam (A-Z)",
                ["HighToLow"] = "Hoog naar Laag",
                ["Newest"] = "Nieuwste",
                ["ApplyFilters"] = "Filters Toepassen",
                ["ClearFilters"] = "Wis Filters",
                ["GamesFound"] = "Spellen Gevonden",
                ["For"] = "voor",
                ["MoreInfo"] = "Meer Info",
                ["Previous"] = "Vorige",
                ["Next"] = "Volgende",
                ["NoGamesFound"] = "Geen spellen gevonden",
                ["TryDifferentSearch"] = "Probeer een andere zoekopdracht of filter",
                ["RTP"] = "RTP",
                ["Jackpot"] = "Jackpot",

                // FAQ Page
                ["AccountRegistration"] = "Account & Registratie",
                ["HowToCreateAccount"] = "Hoe maak ik een account aan?",
                ["ClickRegisterAndFillForm"] = "Klik op 'Registreren' en vul het formulier in",
                ["MustBe18Years"] = "U moet 18 jaar of ouder zijn",
                ["ReceiveConfirmationEmail"] = "U ontvangt een bevestigingsmail",
                ["CanIHaveMultipleAccounts"] = "Kan ik meerdere accounts hebben?",
                ["NoMultipleAccountsAllowed"] = "Nee, slechts één account per persoon is toegestaan",
                ["MultipleAccountsSuspension"] = "Meerdere accounts kunnen leiden tot schorsing",
                ["HowToResetPassword"] = "Hoe reset ik mijn wachtwoord?",
                ["ClickForgotPasswordAndEmail"] = "Klik op 'Wachtwoord Vergeten' en voer uw e-mail in",
                ["ReceiveResetLink"] = "U ontvangt een reset link per e-mail",
                ["DepositsWithdrawals"] = "Stortingen & Opnames",
                ["WhichPaymentMethods"] = "Welke betaalmethoden accepteren jullie?",
                ["WeAcceptPaymentMethods"] = "Wij accepteren de volgende betaalmethoden",
                ["CreditCards"] = "Creditcards",
                ["BankTransfer"] = "Bankoverschrijving",
                ["MinMaxDepositAmount"] = "Wat is het minimum/maximum stortingsbedrag?",
                ["MinimumDeposit10Euro"] = "De minimale storting is €10",
                ["MaximumVariesByMethod"] = "Het maximum varieert per betaalmethode",
                ["WithdrawalProcessingTime"] = "Hoe lang duurt het verwerken van opnames?",
                ["WithdrawalsProcessedWithin24Hours"] = "Opnames worden binnen 24 uur verwerkt",
                ["ProcessingTimeVaries"] = "De verwerkingstijd varieert",
                ["EWallets"] = "E-wallets",
                ["Hours"] = "uur",
                ["CreditCard"] = "Creditcard",
                ["WorkingDays"] = "werkdagen",
                ["GamesGameplay"] = "Spellen & Gameplay",
                ["CanIPlayGamesFree"] = "Kan ik spellen gratis spelen?",
                ["YesPlayDemoMode"] = "Ja, de meeste spellen hebben een demo-modus",
                ["TryGamesBefore"] = "Probeer spellen voordat u echt geld inzet",
                ["WhatIsRTP"] = "Wat is RTP?",
                ["RTPDefinition"] = "RTP = Return to Player percentage",
                ["RTPExplanation"] = "Het geeft aan hoeveel van de inzetten wordt uitgekeerd",
                ["AreGamesFair"] = "Zijn de spellen eerlijk?",
                ["GamesUseCertifiedRNG"] = "Alle spellen gebruiken gecertificeerde Random Number Generators",
                ["GuaranteesFairResults"] = "Dit garandeert eerlijke en willekeurige resultaten",
                ["BonusesPromotions"] = "Bonussen & Promoties",
                ["WhatAreWagering"] = "Wat zijn wagering requirements?",
                ["WageringDefinition"] = "Het aantal keer dat u een bonus moet inzetten voordat opname",
                ["WageringExample"] = "Bijvoorbeeld: €100 bonus met 30x wagering = €3000 inzetten",
                ["CanIDeclineBonus"] = "Kan ik een bonus weigeren?",
                ["YesCanDeclineBonus"] = "Ja, u kunt bonussen altijd weigeren",
                ["ContactSupportToRemove"] = "Neem contact op met support om een bonus te verwijderen",
                ["SecurityResponsibleGaming"] = "Beveiliging & Verantwoord Spelen",
                ["HowProtectPersonalData"] = "Hoe beschermen jullie mijn persoonlijke gegevens?",
                ["WeUseSSLEncryption"] = "Wij gebruiken SSL-versleuteling en veilige servers",
                ["DataNotShared"] = "Uw gegevens worden nooit gedeeld zonder toestemming",
                ["CanISetLimits"] = "Kan ik speellimieten instellen?",
                ["YesEncourageResponsiblePlay"] = "Ja, wij moedigen verantwoord spelen aan",
                ["CanSetLimits"] = "U kunt de volgende limieten instellen",
                ["DailyWeeklyMonthlyLimits"] = "Dagelijkse/wekelijkse/maandelijkse stortingslimieten",
                ["BettingLimitsPerSession"] = "Inzetlimieten per sessie",
                ["LossLimits"] = "Verlieslimieten",
                ["TimeoutPeriods"] = "Time-out periodes",
                ["SelfExclusion"] = "Zelfuitsluiting",
                ["WhatIfGamblingProblem"] = "Wat als ik denk een gokprobleem te hebben?",
                ["SeveralOrganizationsCanHelp"] = "Verschillende organisaties kunnen helpen",
                ["HelplineLoketKansspelen"] = "Hulplijn Loket Kansspelen",
                ["AnonymousGamblers"] = "Anonieme Gokkers",
                ["ContactUsToCloseAccount"] = "Neem contact met ons op om uw account te sluiten",
                ["QuestionNotAnswered"] = "Vraag niet beantwoord?",
                ["SupportTeam24_7"] = "Ons supportteam staat 24/7 voor u klaar",
                ["ContactUs"] = "Neem Contact Op",
            },
            ["en"] = new Dictionary<string, string>
            {
                // Common
                ["Home"] = "Home",
                ["Games"] = "Games",
                ["Login"] = "Login",
                ["Register"] = "Register",
                ["AdminLogin"] = "Admin Login",
                ["Username"] = "Username",
                ["Password"] = "Password",
                ["Email"] = "Email",
                ["RememberMe"] = "Remember Me",
                ["Error"] = "Error",
                ["BackToHome"] = "Back to Home",
                ["WelcomeBack"] = "Welcome Back",
                ["ForgotPassword"] = "Forgot Password",
                ["DontHaveAccount"] = "Don't have an account",
                ["OrLoginWith"] = "Or login with",
                ["GetStarted"] = "Get Started",
                ["PlayNow"] = "Play Now",
                ["Roulette"] = "Roulette",
                ["Slots"] = "Slots",
                ["Blackjack"] = "Blackjack",
                ["Profile"] = "Profile",
                ["Settings"] = "Settings",
                ["Logout"] = "Logout",
                ["BackToGames"] = "Back to Games",
                ["GameDetails"] = "Game Details",
                ["Popular"] = "Popular",
                ["New"] = "New",
                ["MinBet"] = "Min Bet",
                ["MaxBet"] = "Max Bet",
                ["Players"] = "Players",
                ["Rating"] = "Rating",
                ["AddToFavorites"] = "Add to Favorites",
                ["LoginToPlay"] = "Login to Play",
                ["HowToPlay"] = "How to Play",
                ["NoRulesAvailable"] = "No rules available",
                ["SimilarGames"] = "Similar Games",
                ["ComingSoon"] = "Coming Soon",
                ["EnterEmail"] = "Enter email",
                ["EnterPassword"] = "Enter password",
                ["WelcomeToSafeCasino"] = "Welcome to SafeCasino",
                ["About"] = "About",
                ["Privacy"] = "Privacy",
                ["Contact"] = "Contact",
                ["FAQ"] = "FAQ",

                // Home Page
                ["HeroDescription"] = "Experience the thrill of top games in the safest online casino",
                ["WhyChooseUs"] = "Why Choose Us?",
                ["SafeAndSecure"] = "Safe and Secure",
                ["SafeDescription"] = "SSL encryption and secure payments",
                ["FastPayouts"] = "Fast Payouts",
                ["PayoutsDescription"] = "Receive your winnings within 24 hours",
                ["Support247"] = "24/7 Support",
                ["SupportDescription"] = "Always available for your questions",
                ["PopularGames"] = "Popular Games",
                ["RouletteDescription"] = "Spin the wheel and win big",
                ["SlotsDescription"] = "Hundreds of slots with jackpots",
                ["BlackjackDescription"] = "Classic card game with strategy",
                ["ActivePlayers"] = "Active Players",
                ["PaidOut"] = "Paid Out",
                ["ReadyToStart"] = "Ready to Start?",
                ["CTADescription"] = "Join today and receive your welcome bonus",
                ["JoinNow"] = "Join Now",
                ["FooterTagline"] = "The most trusted online casino",
                ["QuickLinks"] = "Quick Links",
                ["AllRightsReserved"] = "All rights reserved",

                // Games Page
                ["CasinoGames"] = "Casino Games",
                ["DiscoverGames"] = "Discover our collection of premium casino games",
                ["Search"] = "Search",
                ["SearchGames"] = "Search games...",
                ["Categories"] = "Categories",
                ["AllCategories"] = "All Categories",
                ["Provider"] = "Provider",
                ["AllProviders"] = "All Providers",
                ["BetRange"] = "Bet Range",
                ["Min"] = "Min",
                ["Max"] = "Max",
                ["SpecialFeatures"] = "Special Features",
                ["HasJackpot"] = "Has Jackpot",
                ["OnlyNew"] = "Only New",
                ["OnlyPopular"] = "Only Popular",
                ["SortBy"] = "Sort By",
                ["NameAZ"] = "Name (A-Z)",
                ["HighToLow"] = "High to Low",
                ["Newest"] = "Newest",
                ["ApplyFilters"] = "Apply Filters",
                ["ClearFilters"] = "Clear Filters",
                ["GamesFound"] = "Games Found",
                ["For"] = "for",
                ["MoreInfo"] = "More Info",
                ["Previous"] = "Previous",
                ["Next"] = "Next",
                ["NoGamesFound"] = "No games found",
                ["TryDifferentSearch"] = "Try a different search or filter",
                ["RTP"] = "RTP",
                ["Jackpot"] = "Jackpot",

                // FAQ Page (abbreviated - add more as needed)
                ["AccountRegistration"] = "Account & Registration",
                ["HowToCreateAccount"] = "How do I create an account?",
                ["DepositsWithdrawals"] = "Deposits & Withdrawals",
                ["GamesGameplay"] = "Games & Gameplay",
                ["BonusesPromotions"] = "Bonuses & Promotions",
                ["SecurityResponsibleGaming"] = "Security & Responsible Gaming",
                ["QuestionNotAnswered"] = "Question not answered?",
                ["SupportTeam24_7"] = "Our support team is available 24/7",
                ["ContactUs"] = "Contact Us",
            },
            ["fr"] = new Dictionary<string, string>
            {
                // Basic French translations
                ["Home"] = "Accueil",
                ["Games"] = "Jeux",
                ["Login"] = "Connexion",
                ["Register"] = "S'inscrire",
                ["PlayNow"] = "Jouer Maintenant",
                ["Popular"] = "Populaire",
                ["New"] = "Nouveau",
                ["About"] = "À Propos",
                ["Contact"] = "Contact",
                ["Privacy"] = "Confidentialité",
                ["FAQ"] = "FAQ",
            }
        };

        public string GetString(string key, string language)
        {
            if (!_translations.ContainsKey(language))
                language = "nl";

            if (_translations[language].ContainsKey(key))
                return _translations[language][key];

            return key;
        }

        public Dictionary<string, string> GetAllStrings(string language)
        {
            if (!_translations.ContainsKey(language))
                language = "nl";

            return new Dictionary<string, string>(_translations[language]);
        }
    }
}
